encrypt_key: '%env(resolve:ENCRYPT_KEY)%'
# The encryptor service created by the factory according to the passed method and using the encrypt_key
SpecShaper\EncryptBundle\Encryptors\EncryptorInterface:
  factory: ['@SpecShaper\EncryptBundle\Encryptors\EncryptorFactory','createService']
  arguments:
    $encryptKey: '%spec_shaper_encrypt.encrypt_key%'
    $encryptorClass: '%spec_shaper_encrypt.encryptor_class%' #optional